version: "3"

services: 
  jupyter_notebook:
    container_name: jupyter_notebook
    build: .
    ports: 
      - "8888:8888"
    environment: 
      - JUPYTER_ENABLE_LAB=yes
    volumes: 
      - .:/home/jovyan/work
